#######################
# Config: Development #
#######################
# (production settings go in _config.build.yml)

name: Betrayed by Tech
url: 'https://www.youbetrayedus.org'
fbtitle: 'Big tech just betrayed us.'
description: 'Apple and Microsoft actually WANT to give your data to the N.S.A.'
twittertext: 'Apple and Microsoft actually WANT to give your data to the N.S.A.'
timezone: America/Los_Angeles
googleanalytics: UA-XXXXXXXX-XX
author:
  - googleid: 102356128596404327231
  - twitterid: 382376904
  - twitter: fightfortheftr

exclude: [
  'img', 'css', 'fonts', '**.haml',
  '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico',
]

###########
# Content #
###########

future: true
show_drafts: true
permalink: /:title/ # See Jekyll documentation for permalink styles

#############
# Compiling #
#############

highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions:
    - footnotes
#    - autolink
#    - smart
